name: Build project with preview URL

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - WebGL
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  build-site:
    needs: [buildForAllSupportedPlatforms]
    name: Add build to site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python and dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - run: |
          pip install firebase-admin

      - name: Get Secret Key
        id: write_key_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "cloud_key.json"
          encodedString: ${{ secrets.CLOUD_KEY }}

      - uses: actions/download-artifact@v3
        with:
          name: Build-WebGL

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Convert branch to lowercase
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ steps.extract_branch.outputs.branch }}

      - name: Run Upload Script
        run: python ./uploader.py '${{ steps.string.outputs.lowercase }}' '${{ steps.write_key_file.outputs.filePath }}'

      - name: Read index url
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./url.txt

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - run: cd svelte-app && npm install && cd ..

      - name: Add iframe to svelte file
        run: cd svelte-app/src/routes && echo "<iframe mozallowfullscreen='true' allow='autoplay; fullscreen' src='${{ steps.package.outputs.content }}' style='border:0px black none;' name='Game' scrolling='no' msallowfullscreen='true' allowfullscreen='true' webkitallowfullscreen='true' allowtransparency='true' frameborder='0' marginheight='px' marginwidth='320px' height='700px' width='960px'></iframe>" > index.svelte && cd ../../../

      - run: cd svelte-app && npm run build

      - name: Deploy to Firebase and Create Preview URL
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FB_SERVICE_ACCOUNT }}"
          expires: 10d
          channelId: ${{ steps.string.outputs.lowercase }}
          entryPoint: "./svelte-app"
